# This file contains values from Cookiecutter

default_context:
  project_name: "news-aggregator-service"
  project_description: "A cool news aggregator service."
  organization: "TheDailyBite"
  license: "MIT"
  minimal_python_version: 3.8
  github_name: "TheDailyBite"
  email: "124548904+bamchip@users.noreply.github.com"
  version: "0.1.0"
  line_length: "100"
  create_example_template: "none"
