version: '3.7'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8002:8002"
    environment:
      - AWS_ACCESS_KEY_ID=accesskey
      - AWS_SECRET_ACCESS_KEY=secretkey
      - AWS_DEFAULT_REGION=us-east-1
    command: -jar DynamoDBLocal.jar -port 8002

  s3-local:
    image: minio/minio
    volumes:
      - ./s3-local-data:/data
    ports:
      - 9000:9000
      - 9001:9001
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: accesskey
      MINIO_ROOT_PASSWORD: secretkey
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3       

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8002"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: accesskey
      AWS_SECRET_ACCESS_KEY: secretkey
    depends_on:
      - dynamodb-local

  news-aggregator-service:
    image: news-aggregator-service:latest-lambda-x86_64
    ports:
      - "8081:8081"
    environment:
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: accesskey
      AWS_SECRET_ACCESS_KEY: secretkey
      REGION_NAME: "us-east-1"      
      DYNAMODB_HOST: "http://dynamodb-local:8002"
      S3_ENDPOINT_URL: "http://s3-local:9000"
      MINIMUM_ARTICLE_INVENTORY_SIZE_TO_SOURCE: "2"
      
    env_file:
      - secret-envs.env
    command: "app.aggregation_scheduler"
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - dynamodb-local
      - s3-local              


  the_daily_bite_web_app:
    image: the_daily_bite_web_app:latest
    ports:
      - "3000:3000"
      - "8000:8000"
    command: "reflex run --env prod"
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: "3"    
    environment:
      LOCAL_TESTING: "true"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: accesskey
      AWS_SECRET_ACCESS_KEY: secretkey
      REGION_NAME: "us-east-1"      
      DYNAMODB_HOST: "http://dynamodb-local:8002"
      S3_ENDPOINT_URL: "http://s3-local:9000"
      ARTICLES_PER_PAGE: "25"
      API_URL: "http://0.0.0.0:8000"
