version: '3.7'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=accesskey
      - AWS_SECRET_ACCESS_KEY=secretkey
      - AWS_DEFAULT_REGION=us-west-1

  s3-local:
    image: minio/minio
    volumes:
      - ./s3-local-data:/data
    ports:
      - 9000:9000
      - 9001:9001
    expose:
      - "9000"
      - "9001"
    environment:
      MINIO_ROOT_USER: accesskey
      MINIO_ROOT_PASSWORD: secretkey
    command: server --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3       

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "us-west-1"
      AWS_ACCESS_KEY_ID: accesskey
      AWS_SECRET_ACCESS_KEY: secretkey
    depends_on:
      - dynamodb-local

  news-aggregator-service:
    image: news-aggregator-service:latest-lambda-x86_64
    ports:
      - "8080:8080"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "us-west-1"
      AWS_ACCESS_KEY_ID: accesskey
      AWS_SECRET_ACCESS_KEY: secretkey
      REGION_NAME: "us-west-1"      
      DYNAMODB_HOST: "http://dynamodb-local:8000"
      S3_ENDPOINT_URL: "http://s3-local:9000"
      
    env_file:
      - secret-envs.env
    command: "app.aggregate_bing_news_self"
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - dynamodb-local
      - s3-local    
